compute_engine_instance:
  image_project: airyxos-images
  image: airyxbuild-0-4-b3
  platform: freebsd
  cpu: 8
  memory: 16G
  disk: 100

clone_task_template: &CLONE_TASK_TEMPLATE
  clone_script: |
    if [ -z "$CIRRUS_PR" ]; then
      git clone --recursive --branch=$CIRRUS_BRANCH https://x-access-token:${CIRRUS_REPO_CLONE_TOKEN}@github.com/${CIRRUS_REPO_FULL_NAME}.git $CIRRUS_WORKING_DIR
      git reset --hard $CIRRUS_CHANGE_IN_REPO
    else
      git clone --recursive https://x-access-token:${CIRRUS_REPO_CLONE_TOKEN}@github.com/${CIRRUS_REPO_FULL_NAME}.git $CIRRUS_WORKING_DIR
      git fetch origin pull/$CIRRUS_PR/head:pull/$CIRRUS_PR
      git reset --hard $CIRRUS_CHANGE_IN_REPO
    fi

build_task:
  timeout_in: 120m
  environment:
    PKG_CONFIG_PATH: /usr/libdata/pkgconfig:/usr/local/libdata/pkgconfig
    JAVA_HOME: /Library/Java/JavaVirtualMachines/openjdk-17.0.1.jdk/Contents/Home
    PORTSROOT: /usr/obj/$(uname -m).$(uname -m)/portsroot
  << : *CLONE_TASK_TEMPLATE
  script:
    - fetch -o /tmp/openjdk-17.jdk.txz https://github.com/mszoek/airyx/releases/download/jdk-17.0.1/openjdk-17.0.1.jdk.txz
    - make -f Makefile.ports prepports
    - mkdir -p ${PORTSROOT}/Library/Java/JavaVirtualMachines
    - tar -C ${PORTSROOT}/Library/Java/JavaVirtualMachines -xf /tmp/openjdk-17.jdk.txz
    - ln -sf $JAVA_HOME/bin/java ${PORTSROOT}/usr/bin/
    - ln -sf $JAVA_HOME/bin/javac ${PORTSROOT}/usr/bin/javac
    - make -j$(sysctl -n hw.ncpus) -f Makefile.ports buildports
    - make -f Makefile.ports makepackages
    - echo FIXME: upload to cloudsmith now
  only_if: $CIRRUS_BRANCH =~ 'airyx/.*'
  cache:
    folder: /usr/obj
